#!/usr/bin/env bash
# MAMMON Weekly Financial Tracker
# Generates weekly report vs Investment Master Plan v2.0 targets
set -euo pipefail

DOMINION_DIR="/data/workspace/dominion"
TODAY=$(date -u +%Y-%m-%d)
REPORT_FILE="$DOMINION_DIR/reports/mammon-weekly-${TODAY}.md"
API_REPORT_DIR="$DOMINION_DIR/api/reports"
NOTIF_DIR="$DOMINION_DIR/notifications"
API_URL="https://dominion-api-production.up.railway.app/api/events"

# Plan constants
MONTHLY_DCA=50000000        # Rp 50M
MONTHLY_WEDDING=30000000    # Rp 30M
WEDDING_TARGET=350000000    # Rp 350M
WAR_CHEST_TARGET=40000000   # Rp 40M (already funded)
BTC_ATH=109000              # USD approximate ATH
PLAN_START="2025-02-01"     # Plan v2.0 start date
WEDDING_DATE="2026-11-01"   # Target wedding date

# --- 1. Fetch BTC price ---
echo "⚡ Fetching BTC price..."
BTC_JSON=$(curl -sf "https://api.coingecko.com/api/v3/simple/price?ids=bitcoin&vs_currencies=usd,idr" 2>/dev/null || echo '{}')
BTC_USD=$(echo "$BTC_JSON" | grep -o '"usd":[0-9.]*' | head -1 | cut -d: -f2)
BTC_IDR=$(echo "$BTC_JSON" | grep -o '"idr":[0-9.]*' | head -1 | cut -d: -f2)

if [ -z "$BTC_USD" ]; then
  BTC_USD=97000
  BTC_IDR=1550000000000
  PRICE_NOTE="(fallback — API unavailable)"
else
  PRICE_NOTE=""
fi

BTC_USD_INT=${BTC_USD%.*}
BTC_IDR_INT=${BTC_IDR%.*}

# --- 2. Drawdown from ATH ---
DRAWDOWN=$(awk "BEGIN { printf \"%.1f\", (1 - $BTC_USD / $BTC_ATH) * 100 }")
DRAWDOWN_NEG="-${DRAWDOWN}%"
if awk "BEGIN { exit ($DRAWDOWN < 0) ? 0 : 1 }"; then
  DRAWDOWN_NEG="NEW ATH TERRITORY"
  DRAWDOWN="0"
fi

# --- 3. War chest triggers ---
TRIGGER_30=$(awk "BEGIN { printf \"%.0f\", $BTC_ATH * 0.70 }")
TRIGGER_40=$(awk "BEGIN { printf \"%.0f\", $BTC_ATH * 0.60 }")
TRIGGER_50=$(awk "BEGIN { printf \"%.0f\", $BTC_ATH * 0.50 }")

WAR_STATUS="🟢 HOLD — No deployment needed"
DEPLOY_PCT=0
if awk "BEGIN { exit ($BTC_USD <= $TRIGGER_50) ? 0 : 1 }"; then
  WAR_STATUS="🔴 FULL DEPLOY (100%) — BTC below -50% from ATH!"
  DEPLOY_PCT=100
elif awk "BEGIN { exit ($BTC_USD <= $TRIGGER_40) ? 0 : 1 }"; then
  WAR_STATUS="🟠 DEPLOY 50% — BTC below -40% from ATH"
  DEPLOY_PCT=50
elif awk "BEGIN { exit ($BTC_USD <= $TRIGGER_30) ? 0 : 1 }"; then
  WAR_STATUS="🟡 DEPLOY 25% — BTC below -30% from ATH"
  DEPLOY_PCT=25
fi

# --- 4. Weeks until wedding ---
WEDDING_EPOCH=$(date -d "$WEDDING_DATE" +%s 2>/dev/null || date -u -d "$WEDDING_DATE" +%s)
NOW_EPOCH=$(date -u +%s)
WEEKS_LEFT=$(( (WEDDING_EPOCH - NOW_EPOCH) / 604800 ))

# --- 5. Wedding fund progress ---
PLAN_EPOCH=$(date -d "$PLAN_START" +%s 2>/dev/null || date -u -d "$PLAN_START" +%s)
MONTHS_ELAPSED=$(( (NOW_EPOCH - PLAN_EPOCH) / 2592000 ))
WEDDING_SAVED=$(( MONTHS_ELAPSED * MONTHLY_WEDDING ))
if [ "$WEDDING_SAVED" -gt "$WEDDING_TARGET" ]; then
  WEDDING_SAVED=$WEDDING_TARGET
fi
WEDDING_PCT=$(awk "BEGIN { printf \"%.0f\", ($WEDDING_SAVED / $WEDDING_TARGET) * 100 }")
WEDDING_REMAINING=$(( WEDDING_TARGET - WEDDING_SAVED ))

# Progress bar (20 chars)
FILLED=$(( WEDDING_PCT / 5 ))
EMPTY=$(( 20 - FILLED ))
PROGRESS_BAR=$(printf '█%.0s' $(seq 1 $FILLED 2>/dev/null || echo))$(printf '░%.0s' $(seq 1 $EMPTY 2>/dev/null || echo))

# DCA progress this month
DAY_OF_MONTH=$(date -u +%d | sed 's/^0//')
DCA_MONTH_STATUS="📅 Day $DAY_OF_MONTH — "
if [ "$DAY_OF_MONTH" -le 7 ]; then
  DCA_MONTH_STATUS+="Execute DCA buy this week if not done"
elif [ "$DAY_OF_MONTH" -le 14 ]; then
  DCA_MONTH_STATUS+="First half of month — DCA should be in progress"
else
  DCA_MONTH_STATUS+="Month progressing — ensure Rp 50M DCA completed"
fi

# BTC accumulation estimate
TOTAL_DCA_IDR=$(( MONTHS_ELAPSED * MONTHLY_DCA ))
BTC_ACCUMULATED=$(awk "BEGIN { printf \"%.4f\", $TOTAL_DCA_IDR / $BTC_IDR_INT }")

# Format numbers with dots for IDR
fmt_idr() {
  echo "$1" | rev | sed 's/.\{3\}/&./g' | rev | sed 's/^\.//'
}

WEDDING_SAVED_FMT=$(fmt_idr $WEDDING_SAVED)
WEDDING_REMAINING_FMT=$(fmt_idr $WEDDING_REMAINING)
TOTAL_DCA_FMT=$(fmt_idr $TOTAL_DCA_IDR)

# --- 6. Generate report ---
cat > "$REPORT_FILE" << REPORT
# 💀 MAMMON Weekly Financial Report
**Date:** ${TODAY}
**Generated by:** MAMMON — Financial General of the Dominion

---

## 📊 BTC Position Summary ${PRICE_NOTE}

| Metric | Value |
|--------|-------|
| BTC Price (USD) | \$${BTC_USD_INT} |
| BTC Price (IDR) | Rp ${BTC_IDR_INT} |
| ATH Reference | \$${BTC_ATH} |
| Drawdown from ATH | ${DRAWDOWN_NEG} |
| Est. BTC Accumulated | ₿${BTC_ACCUMULATED} |
| Target (2030) | ₿5 – ₿12 |

---

## 💰 DCA Tracker (Rp 50M/month)

- **Monthly Target:** Rp 50.000.000
- **Months Since Plan Start:** ${MONTHS_ELAPSED}
- **Total DCA Invested:** Rp ${TOTAL_DCA_FMT}
- **Status:** ${DCA_MONTH_STATUS}

> Strategy: Consistent Rp 50M/month into BTC. No timing. No altcoins. Pure accumulation.

---

## 💍 Wedding Fund Tracker

**Target:** Rp 350.000.000 by Oct 2026
**Saved (est):** Rp ${WEDDING_SAVED_FMT}
**Remaining:** Rp ${WEDDING_REMAINING_FMT}
**Weeks Until Wedding:** ${WEEKS_LEFT}

\`\`\`
[${PROGRESS_BAR}] ${WEDDING_PCT}%
\`\`\`

Monthly contribution: Rp 30.000.000 — on track if consistent.

---

## ⚔️ War Chest Status

**Target Float:** Rp 40.000.000 (FUNDED ✅)
**Current BTC Drawdown:** ${DRAWDOWN_NEG}

**Deployment Triggers:**
| Trigger | Price | Status |
|---------|-------|--------|
| -30% from ATH | \$${TRIGGER_30} | $([ "$DEPLOY_PCT" -ge 25 ] && echo "🟡 TRIGGERED" || echo "⬜ Waiting") |
| -40% from ATH | \$${TRIGGER_40} | $([ "$DEPLOY_PCT" -ge 50 ] && echo "🟠 TRIGGERED" || echo "⬜ Waiting") |
| -50% from ATH | \$${TRIGGER_50} | $([ "$DEPLOY_PCT" -ge 100 ] && echo "🔴 TRIGGERED" || echo "⬜ Waiting") |

**Status:** ${WAR_STATUS}

---

## 🔥 Fire Sale Theory Reminder

> *"AI will destroy the middle class by 2030. Those who own BTC and build AI will survive. Everyone else becomes a serf."*

The clock is ticking. Every week of DCA is another brick in your fortress.
The world won't warn you before it changes. Stack sats. Build products. Stay dangerous.

**NO ALTCOINS. EVER.**

---

## ✅ Action Items This Week

1. [ ] Execute BTC DCA if not done this month (Rp 50M)
2. [ ] Transfer Rp 30M to wedding fund
3. [ ] Verify war chest float at Rp 40M
4. [ ] Review OKU Trade + ForuAI income targets
5. $([ "$DEPLOY_PCT" -gt 0 ] && echo "[ ] ⚠️ WAR CHEST DEPLOYMENT TRIGGERED — Deploy ${DEPLOY_PCT}% into BTC!" || echo "[ ] Monitor BTC price for war chest triggers")

---

*Report generated by MAMMON | The Dominion Financial Engine*
*Next report: $(date -u -d "+7 days" +%Y-%m-%d 2>/dev/null || date -u +%Y-%m-%d)*
REPORT

echo "📄 Report saved: $REPORT_FILE"

# --- 7. Copy to API reports ---
mkdir -p "$API_REPORT_DIR"
cp "$REPORT_FILE" "$API_REPORT_DIR/"
echo "📋 Copied to API reports"

# --- 8. Log event to API ---
EVENT_JSON=$(cat <<EOF
{
  "type": "mammon_weekly_report",
  "source": "mammon",
  "data": {
    "date": "${TODAY}",
    "btc_usd": ${BTC_USD_INT},
    "drawdown_pct": ${DRAWDOWN},
    "war_chest_deploy_pct": ${DEPLOY_PCT},
    "wedding_fund_pct": ${WEDDING_PCT},
    "weeks_to_wedding": ${WEEKS_LEFT},
    "btc_accumulated_est": ${BTC_ACCUMULATED},
    "dca_months": ${MONTHS_ELAPSED}
  }
}
EOF
)

curl -sf -X POST "$API_URL" \
  -H "Content-Type: application/json" \
  -d "$EVENT_JSON" > /dev/null 2>&1 && echo "📡 Event logged to API" || echo "⚠️ API logging failed (non-critical)"

# --- 9. Queue notification ---
mkdir -p "$NOTIF_DIR"
NOTIF_FILE="$NOTIF_DIR/mammon-weekly-${TODAY}.json"
cat > "$NOTIF_FILE" << EOF
{
  "type": "mammon_weekly_report",
  "priority": "normal",
  "timestamp": "$(date -u +%Y-%m-%dT%H:%M:%SZ)",
  "title": "💀 MAMMON Weekly Report — ${TODAY}",
  "summary": "BTC: \$${BTC_USD_INT} (${DRAWDOWN_NEG}) | Wedding: ${WEDDING_PCT}% | War Chest: ${WAR_STATUS}",
  "report_path": "${REPORT_FILE}",
  "channel": "telegram"
}
EOF
echo "🔔 Notification queued: $NOTIF_FILE"

echo ""
echo "✅ MAMMON weekly report complete."
