#!/usr/bin/env bash
# WRAITH-EYE — Infrastructure Monitor
# Checks Dominion services, OKU Trade, and ForuAI

set -euo pipefail

DOMINION_ROOT="${DOMINION_ROOT:-/data/workspace/dominion}"
API_BASE="https://dominion-api-production.up.railway.app"
DATE=$(date -u +%Y-%m-%d)
TIMESTAMP=$(date -u +%Y-%m-%dT%H:%M:%SZ)
REPORT="$DOMINION_ROOT/reports/wraith-eye-monitor-${DATE}.md"
SLOW_THRESHOLD=2000  # ms

declare -A SERVICES=(
  ["Dominion API"]="https://dominion-api-production.up.railway.app/"
  ["Dominion Frontend"]="https://dominion-frontend-production.up.railway.app/"
  ["OKU Trade"]="https://oku.trade"
  ["ForuAI"]="https://foruai.com"
)

OVERALL="HEALTHY"
ALERTS=""
RESULTS=""

check_service() {
  local name="$1" url="$2"
  local start end status time_ms

  start=$(date +%s%N)
  status=$(curl -s -o /dev/null -w "%{http_code}" --connect-timeout 10 --max-time 15 "$url" 2>/dev/null || echo "000")
  end=$(date +%s%N)
  time_ms=$(( (end - start) / 1000000 ))

  local flag="✅ OK"
  if [[ "$status" != "200" && "$status" != "301" && "$status" != "302" && "$status" != "304" ]]; then
    flag="🔴 DOWN"
    OVERALL="DEGRADED"
    ALERTS+="$(cat <<EOF

👁️ WRAITH-EYE ALERT — SERVICE DOWN

🔴 ${name} is NOT responding
⏱️ Last check: ${TIMESTAMP}
📊 Status: ${status} | Response: ${time_ms}ms

Recommend immediate investigation.
EOF
)"
  elif [[ "$time_ms" -gt "$SLOW_THRESHOLD" ]]; then
    flag="🟡 SLOW"
    if [[ "$OVERALL" == "HEALTHY" ]]; then OVERALL="SLOW"; fi
  fi

  RESULTS+="| ${name} | ${url} | ${status} | ${time_ms}ms | ${flag} |
"
  echo "  ${flag} ${name}: ${status} (${time_ms}ms)"
}

echo "👁️ WRAITH-EYE scanning at ${TIMESTAMP}..."

for name in "Dominion API" "Dominion Frontend" "OKU Trade" "ForuAI"; do
  check_service "$name" "${SERVICES[$name]}"
done

# Generate report
cat > "$REPORT" <<EOF
# 👁️ WRAITH-EYE Monitoring Report

**Date:** ${DATE}
**Timestamp:** ${TIMESTAMP}
**Overall Status:** ${OVERALL}

## Service Health

| Service | URL | Status | Response | Health |
|---------|-----|--------|----------|--------|
${RESULTS}
## Alerts
$(if [[ -n "$ALERTS" ]]; then echo "$ALERTS"; else echo "_No alerts. All systems nominal._"; fi)

---
*Generated by WRAITH-EYE Infrastructure Monitor*
EOF

cp "$REPORT" "$DOMINION_ROOT/api/reports/" 2>/dev/null || true

# Log event to API
PRIORITY="LOW"
if [[ "$OVERALL" == "DEGRADED" ]]; then PRIORITY="HIGH"; fi
if [[ "$OVERALL" == "SLOW" ]]; then PRIORITY="NORMAL"; fi

curl -s -X POST "${API_BASE}/api/events" \
  -H "Content-Type: application/json" \
  -d "{\"type\":\"wraith-eye-scan\",\"source\":\"wraith-eye\",\"priority\":\"${PRIORITY}\",\"data\":{\"status\":\"${OVERALL}\",\"timestamp\":\"${TIMESTAMP}\"}}" \
  -o /dev/null --max-time 10 2>/dev/null || echo "  ⚠️ Could not log event to API"

echo ""
echo "📊 Overall: ${OVERALL}"
echo "📄 Report: ${REPORT}"

if [[ -n "$ALERTS" ]]; then
  echo "$ALERTS"
fi
